notifications:
  email: false
os: linux
language: python
python: 3.8
install:
# install binary packages
- travis_retry pip install --upgrade pip
- travis_retry pip install setuptools wheel
# install package
- travis_retry pip install -e .
# for tests:
- travis_retry pip install codecov coverage flake8
- pip freeze
script:
#- coverage run --source=dcor_control setup.py test
#- coverage report -m
- flake8 dcor_control
- flake8 tests
after_success:
- codecov
before_deploy:
#- python setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: "ci_dcor"
  password:
    secure: "XzssHyoA6kAQO6JDvNNrm8ahmalhr8ko3GYfIW8lcN+AW89pTOpco72gsEqScl6J8ewK9ieyxjh5BN1VNhGnkLapEJeGpSc1iPWN8GwhdU47Eh+EMNJD7rKJCMmE/6Zz3WtKJzx5+CKKSbLQuRQOWSjsgrhzHFSu6pEeG0GZ01/Gp8CUilRd3V8ATV4v5x7+3AQIDwuol1afwniRs6Iyo36Fc1a39YdSt4iUKRzq5+sQGkfSZZszDpW1x9UcYzqnDQv7LP0bXjhN715fffk/ATdMCZkqU6xFu/rSCsrmjvMn5+aySNkCBoIL0LYn7EsirM2ui+vDZz7U4tifm7HAPWAwqrWa1d9Zufn+wrs4bMIn9dSiQh5j4obe6vEfH/iJLJbTFaPJDszgbUktQoMA5go5P0Pme+1HqbGgx1QmHp8ROF0Dmo/1AHmTiFclKavrK0aMFrVybsClAa0/ygtuaafJ0lY4+PCYGQghTvKANV4eeQVINtbPe4QHtrWOKWXn2XNUMk3I6rtgTaQl4weAb2e3xkiLVOtEhUUBlhKFzEOTuETj4FnN1bP6Bdwh5zVzt7A5EJ+uiwuFADcODIIARSolpVzkYxWO6OF8JE9Xp7iMTWUbx2oNcmwAnuPh1DTCO7dAaXXK74JOjSJBMpNHJU6N13PMmblfDad/C5OmV3I="
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
